[project]
name = "thistle"
version = "0.1.0rc4"
description = "A wrapper for sgp4 that handles TLE switching"
readme = "README.md"
authors = [
    { name = "jolsten", email = "jolsten@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.22",
    "pydantic-settings>=2.8.1",
    "sgp4>=2.23",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "hypothesis>=6.124.2",
    "pytest>=8.3.4",
]
